services:
  db:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:3200:8080
