"""add password_hash to journey

Revision ID: 15bb5e96817e
Revises: 8c5996ce0ef0
Create Date: 2026-08-22 13:47:46.097716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bb5e96817e'
down_revision: Union[str, Sequence[str], None] = '8c5996ce0ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journeys', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journeys', 'password_hash')
    # ### end Alembic commands ###
